const COLORS = {
  STACK_TRACE_LINK: '#51cf66',
  BACKGROUND_DARK: '#1a1a1a',
  NODE_DEFAULT: '#93c5fd',
  EDGE_DEFAULT: '#4b5563'
};

const AUTO_ROTATE_DELAY = 1000;

export { COLORS, AUTO_ROTATE_DELAY };
