'use strict';

const fs = require('fs');
const path = require('path');

const { DEFAULT_CONTROLS, COLORS, AUTO_ROTATE_DELAY } = require('../src/constants');

const TEMPLATE_PATH = path.join(__dirname, '../webview/template.html');
const OUTPUT_PATH = path.join(__dirname, '../src/webview.html');
const SRC_DIR = path.join(__dirname, '../webview/src');

const SCRIPT_FILES = [
  'core.js',
  'GraphState.js',
  'utils.js',
  'ExtensionBridge.js',
  'GraphRenderer.js',
  'GraphRenderer2D.js',
  'GraphRenderer3D.js',
  'init.js'
];

function buildWebview() {
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
  const script = SCRIPT_FILES
    .map(file => fs.readFileSync(path.join(SRC_DIR, file), 'utf8'))
    .join('\n\n');

  const constantsBlock = [
    `const DEFAULT_CONTROLS = ${JSON.stringify(DEFAULT_CONTROLS)};`,
    `const COLORS = ${JSON.stringify(COLORS)};`,
    `const AUTO_ROTATE_DELAY = ${AUTO_ROTATE_DELAY};`
  ].join('\n');

  const wrappedScript = `(function() {\n${constantsBlock}\n${script}\n})();`;

  // Add header comment to indicate this is a generated file
  const generatedHeader = `<!--
  ⚠️  THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY
  Generated by: scripts/build-webview.js
  Source files: webview/src/*.js and webview/template.html
  To modify: Edit source files and run 'npm run build:webview'
-->\n`;

  const result = generatedHeader + template.replace(/{{script}}/g, wrappedScript);

  fs.writeFileSync(OUTPUT_PATH, result, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Webview template built -> ${OUTPUT_PATH}`);
}

buildWebview();
