const CONTROL_DEFAULTS = {
    search: '',
    is3DMode: false,
    nodeSizeByLoc: false,
    hideIsolatedNodes: false,
    showStackTrace: true,
    showNames: true,
    shortNames: true,
    nodeSize: 3.0,
    linkWidth: 0.5,
    nodeOpacity: 1.0,
    edgeOpacity: 0.6,
    linkDistance: 50,
    focusDistance: 120,
    arrowSize: 3,
    textSize: 12,
    sliceDepth: 3,
    enableForwardSlice: true,
    enableBackwardSlice: true,
    showClass: true,
    showAbstractClass: true,
    showInterface: true,
    showUnknown: true,
    showObjectCreate: true,
    showExtends: true,
    showImplements: true,
    showTypeUse: true,
    showMethodCall: true,
    colorClass: '#93c5fd',
    colorAbstractClass: '#d8b4fe',
    colorInterface: '#6ee7b7',
    colorUnknown: '#9ca3af',
    colorObjectCreate: '#fde047',
    colorExtends: '#d8b4fe',
    colorImplements: '#6ee7b7',
    colorTypeUse: '#fdba74',
    colorMethodCall: '#fda4af'
};

const SLIDER_RANGES = {
    nodeSize: { min: 0.1, max: 20, step: 0.1 },
    linkWidth: { min: 0.1, max: 5, step: 0.1 },
    opacity: { min: 0.1, max: 1, step: 0.1 },
    linkDistance: { min: 10, max: 200, step: 5 },
    focusDistance: { min: 20, max: 300, step: 5 },
    arrowSize: { min: 1, max: 20, step: 1 },
    textSize: { min: 8, max: 24, step: 1 },
    sliceDepth: { min: 1, max: 10, step: 1 }
};

module.exports = { CONTROL_DEFAULTS, SLIDER_RANGES };
